# Generated by Django 5.1 on 2024-08-14 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matutino', models.BooleanField(default=False)),
                ('vespertino', models.BooleanField(default=False)),
                ('trilha', models.CharField(max_length=100)),
                ('max_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('CPF', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('matriculado', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.turma')),
            ],
        ),
    ]
