# Generated by Django 4.2.4 on 2024-08-19 03:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.person')),
            ],
            bases=('blog.person',),
        ),
        migrations.RemoveField(
            model_name='person',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='person',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='person',
            name='matriculado',
        ),
        migrations.RemoveField(
            model_name='person',
            name='turma',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.person')),
                ('matriculado', models.BooleanField(default=False)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.turma')),
            ],
            bases=('blog.person',),
        ),
    ]
