# Generated by Django 5.1 on 2024-09-03 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_admin_remove_person_admin_remove_person_entry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='vagas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.turma'),
        ),
    ]
