# Generated by Django 5.1.1 on 2024-09-04 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_student_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time_limit',
            field=models.DateTimeField(default=datetime.timedelta(seconds=30)),
        ),
    ]
