# Generated by Django 5.1.1 on 2024-09-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_student_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
