# Generated by Django 5.1.1 on 2024-09-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_turma_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
