# Generated by Django 5.1.1 on 2024-09-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_admin_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='count',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
