# Generated by Django 5.1 on 2024-09-01 22:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('CPF', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matutino', models.BooleanField(default=False)),
                ('vespertino', models.BooleanField(default=False)),
                ('trilha', models.CharField(max_length=100)),
                ('max_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_app.person')),
            ],
            bases=('api_app.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_app.person')),
                ('matriculado', models.BooleanField(default=False)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.turma')),
            ],
            bases=('api_app.person',),
        ),
    ]
